### ISSUE TITLE
Error while adding extra

### ISSUE THREAD

**Issue by guillaumelachaud** [contrary-cat/LocalTVExtras.bundle#1]
Seems like the plugin is crashing for me:

```
INFO (__init__:28) - Season 4 is a Season Folder
2019-02-25 21:37:09,832 (7f207a7fc700) :  INFO (__init__:171) - Searching for extras for season 4
2019-02-25 21:37:09,832 (7f207a7fc700) :  INFO (__init__:121) - Looking for local extras in path: /data/TV/Le Bureau Des Légendes/Season 4
2019-02-25 21:37:09,835 (7f207a7fc700) :  INFO (__init__:121) - Coulisses.mkv
2019-02-25 21:37:09,840 (7f207a7fc700) :  CRITICAL (agentkit:1078) - Exception in the update function of agent named 'Local TV Extras Agent', called with guid 'com.plexapp.agents.thetvdb://294564?lang=fr' (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-cc260c476/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/agentkit.py", line 1076, in _update
    agent.update(obj, media, lang, **kwargs)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/LocalTVExtras.bundle/Contents/Code/__init__.py", line 172, in update
    FindExtras(metadata.seasons[s], dirs) #check for metadata to add to the season
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/LocalTVExtras.bundle/Contents/Code/__init__.py", line 121, in FindExtras
    AddExtra(extras, key, title, os.path.join(path, f))
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/LocalTVExtras.bundle/Contents/Code/__init__.py", line 52, in AddExtra
    extra_path = unicodedata.normalize('NFC',unicode(extra_path)) # This works for me, but the full function def unicodize(s) in helpers.py in the Plex Local Media agent may be needed for servers on other platforms - to be confirmed
NameError: global name 'unicodedata' is not defined
```

**Comment by contrary-cat** [comment]
I think this should have been fixed with the 28th February commit - can you confirm?

**Comment by guillaumelachaud** [comment]
Sorry for the very delayed answer (I was travelling and away from computer). I can confirm that pulling master, the error is gone. Looking at the logs, it seems to properly detect extras. I am still unable to see any Extras in Plex though. I'll look into #2 as it looks similar.

Thanks!
